module.exports = {
  POSTGRES_IP: process.env.POSTGRES_IP || 'postgres',
  POSTGRES_PORT: process.env.POSTGRES_PORT || 5433,
  POSTGRES_USERNAME: process.env.POSTGRES_USERNAME,
  POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
  POSTGRES_DATABASE: process.env.POSTGRES_DATABASE,

  SESSION_SECRET: process.env.SESSION_SECRET,
};
