# Node image to use
FROM node:16-alpine

# Directory where we run all the commands
WORKDIR /usr/local/apps/analytics-app

# Copy the package.json file to out image's filesystem
COPY package*.json ./

# Run a npm install command based on node env
RUN npm install 

# Set working directory to /prod
WORKDIR /usr/local/apps/analytics-app/prod

# Copy the rest of the source code
COPY . ./

# Build app
RUN npm run build

ENV PORT 3002
EXPOSE $PORT

CMD ["npm", "run", "start"]