# Node image to use
FROM node:16-alpine

# Directory where we run all the commands
WORKDIR /usr/local/apps/gateway-app

# Copy the package.json file to out image's filesystem
COPY package.json ./

# Set working directory to /dev
WORKDIR /usr/local/apps/gateway-app/dev

# Copy tsconfig
COPY tsconfig.json ./

# If we are in development, then copy our node_modules
COPY node_modules ./node_modules

# Copy the rest of the source code
COPY src ./src

ENV PORT 3000
EXPOSE $PORT

CMD ["node", "gateway.ts"]