# Node image to use
FROM node:16-alpine

# Directory where we run all the commands
WORKDIR /usr/local/apps/inventory-app

# Copy the package.json file to out image's filesystem
COPY package.json ./

# Set working directory to /dev
WORKDIR /usr/local/apps/inventory-app/dev

# Copy all project files
COPY . ./

ENV PORT 3000
EXPOSE $PORT

CMD ["node", "gateway.ts"]