# Node image to use
FROM node:16-alpine

# Directory where we run all the commands
WORKDIR /usr/local/apps/inventory-app

# Copy the package.json file to out image's filesystem
COPY package.json ./

# Install node modules
RUN npm install

# Set working directory to /test
WORKDIR /usr/local/apps/inventory-app/test

# Copy the rest of our source code
COPY . ./

# Set & expose port env
ENV PORT 3001
EXPOSE $PORT

# Start the app
CMD ["npm", "run", "test"]